// Generated by scripts/generate-defaults.ts from schema.graphql. Do not edit.

import type { InputDefaults } from './normalize';

export const inputDefaults: InputDefaults = {
  ActivitiesRequest: {
    defaults: {
      types: [
        'BORROW',
        'SUPPLY',
        'WITHDRAW',
        'REPAY',
        'LIQUIDATED',
        'SET_AS_COLLATERAL',
        'UPDATED_DYNAMIC_CONFIG',
        'UPDATED_RISK_PREMIUM',
        'TOKEN_TO_TOKEN_SWAP',
        'SUPPLY_SWAP',
        'BORROW_SWAP',
        'REPAY_WITH_SUPPLY',
        'WITHDRAW_SWAP',
        'LEVERAGE',
      ],
      pageSize: 'FIFTY',
    },
    fields: {},
  },
  AssetBorrowHistoryRequest: {
    defaults: {
      window: 'LAST_DAY',
    },
    fields: {},
  },
  AssetPriceHistoryRequest: {
    defaults: {
      currency: 'USD',
      window: 'LAST_DAY',
    },
    fields: {},
  },
  AssetSupplyHistoryRequest: {
    defaults: {
      window: 'LAST_DAY',
    },
    fields: {},
  },
  BorrowApyHistoryRequest: {
    defaults: {
      window: 'LAST_DAY',
      includeRewards: true,
    },
    fields: {},
  },
  BorrowSwapQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketDebtSwapQuoteInput',
    },
  },
  HubAssetsRequest: {
    defaults: {
      orderBy: {
        assetName: 'ASC',
      },
    },
    fields: {},
  },
  HubSummaryHistoryRequest: {
    defaults: {
      currency: 'USD',
      window: 'LAST_DAY',
    },
    fields: {},
  },
  HubsRequest: {
    defaults: {
      orderBy: {
        name: 'ASC',
      },
    },
    fields: {},
  },
  LeverageQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketLeverageQuoteInput',
    },
  },
  LimitOrderTokenSwapQuoteInput: {
    defaults: {
      kind: 'SELL',
    },
    fields: {},
  },
  LiquidatePositionRequest: {
    defaults: {
      receiveShares: false,
    },
    fields: {},
  },
  MarketDebtSwapQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MarketLeverageQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MarketOrderTokenSwapQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MarketRepayWithSupplyQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MarketSupplySwapQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MarketWithdrawSwapQuoteInput: {
    defaults: {
      accuracy: 'ACCURATE',
    },
    fields: {},
  },
  MultichainAssetRequest: {
    defaults: {
      currency: 'USD',
      includeRewards: true,
    },
    fields: {},
  },
  PaginatedReserveHoldersRequest: {
    defaults: {
      filter: 'SUPPLIED',
      orderBy: {
        amount: 'DESC',
      },
      pageSize: 'TEN',
    },
    fields: {
      orderBy: 'ReserveHoldersOrderBy',
    },
  },
  PendingOrdersRequest: {
    defaults: {
      pageSize: 'FIFTY',
    },
    fields: {},
  },
  PreviewAction: {
    defaults: {},
    fields: {
      supplySwap: 'SupplySwapQuoteRequest',
      borrowSwap: 'BorrowSwapQuoteRequest',
      repayWithSupply: 'RepayWithSupplyQuoteRequest',
      withdrawSwap: 'WithdrawSwapQuoteRequest',
      leverage: 'LeverageQuoteRequest',
    },
  },
  PreviewRequest: {
    defaults: {},
    fields: {
      action: 'PreviewAction',
    },
  },
  ProtocolHistoryRequest: {
    defaults: {
      currency: 'USD',
      window: 'LAST_DAY',
    },
    fields: {},
  },
  RepayWithSupplyQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketRepayWithSupplyQuoteInput',
    },
  },
  ReserveHoldersOrderBy: {
    defaults: {
      amount: 'DESC',
    },
    fields: {},
  },
  ReservesRequest: {
    defaults: {
      filter: 'ALL',
      orderBy: {
        assetName: 'ASC',
      },
    },
    fields: {
      query: 'ReservesRequestQuery',
    },
  },
  ReservesRequestQuery: {
    defaults: {},
    fields: {
      symbolChainIds: 'SymbolInput',
    },
  },
  SpokeSummaryHistoryRequest: {
    defaults: {
      currency: 'USD',
      window: 'LAST_DAY',
    },
    fields: {},
  },
  SupplyApyHistoryRequest: {
    defaults: {
      window: 'LAST_DAY',
      includeRewards: true,
    },
    fields: {},
  },
  SupplySwapQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketSupplySwapQuoteInput',
    },
  },
  SymbolInput: {
    defaults: {
      chainIds: [],
    },
    fields: {},
  },
  TokenSwapQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketOrderTokenSwapQuoteInput',
      limit: 'LimitOrderTokenSwapQuoteInput',
    },
  },
  UserBalancesByChains: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesByHub: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesByHubId: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesBySpoke: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesByTokens: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesByUserPosition: {
    defaults: {
      byReservesType: 'ALL',
    },
    fields: {},
  },
  UserBalancesRequest: {
    defaults: {
      orderBy: {
        balance: 'DESC',
      },
      includeZeroBalances: false,
    },
    fields: {
      filter: 'UserBalancesRequestFilter',
    },
  },
  UserBalancesRequestFilter: {
    defaults: {},
    fields: {
      chains: 'UserBalancesByChains',
      hub: 'UserBalancesByHub',
      hubId: 'UserBalancesByHubId',
      spoke: 'UserBalancesBySpoke',
      userPosition: 'UserBalancesByUserPosition',
      tokens: 'UserBalancesByTokens',
    },
  },
  UserBorrowsRequest: {
    defaults: {
      orderBy: {
        amount: 'DESC',
      },
      includeZeroBalances: false,
    },
    fields: {
      query: 'UserBorrowsRequestQuery',
    },
  },
  UserBorrowsRequestQuery: {
    defaults: {},
    fields: {
      userSymbol: 'UserSymbol',
    },
  },
  UserPositionsRequest: {
    defaults: {
      orderBy: {
        created: 'ASC',
      },
    },
    fields: {},
  },
  UserSummaryHistoryRequest: {
    defaults: {
      window: 'LAST_DAY',
    },
    fields: {},
  },
  UserSuppliesRequest: {
    defaults: {
      orderBy: {
        amount: 'DESC',
      },
      includeZeroBalances: false,
    },
    fields: {
      query: 'UserSuppliesRequestQuery',
    },
  },
  UserSuppliesRequestQuery: {
    defaults: {},
    fields: {
      userSymbol: 'UserSymbol',
    },
  },
  UserSwapsRequest: {
    defaults: {
      pageSize: 'FIFTY',
    },
    fields: {},
  },
  UserSymbol: {
    defaults: {
      chainIds: [],
    },
    fields: {},
  },
  WithdrawSwapQuoteRequest: {
    defaults: {},
    fields: {
      market: 'MarketWithdrawSwapQuoteInput',
    },
  },
};
