import type {
  BorrowActivity,
  Chain,
  Erc20Token,
  Hub,
  HubAsset,
  LiquidatedActivity,
  RepayActivity,
  Reserve,
  ReserveInfo,
  Spoke,
  SupplyActivity,
  SwapActivity,
  SwapByIntent,
  SwapByIntentWithApprovalRequired,
  SwapByTransaction,
  UserPosition,
  WithdrawActivity,
} from '@aave/graphql-next';
import introspectedSchema from '@aave/graphql-next/schema';
import { cacheExchange } from '@urql/exchange-graphcache';

export const cache = /*#__PURE__*/ cacheExchange({
  schema: introspectedSchema,
  keys: {
    // Entities with id field as key
    Reserve: (data: Reserve) => data.id.toString(),
    BorrowActivity: (data: BorrowActivity) => data.id,
    LiquidatedActivity: (data: LiquidatedActivity) => data.id,
    ReserveInfo: (data: ReserveInfo) => data.id.toString(),
    SupplyActivity: (data: SupplyActivity) => data.id,
    SwapActivity: (data: SwapActivity) => data.id,
    SwapByIntent: (data: SwapByIntent) => data.id,
    SwapByIntentWithApprovalRequired: (
      data: SwapByIntentWithApprovalRequired,
    ) => data.id,
    SwapByTransaction: (data: SwapByTransaction) => data.id,
    UserPosition: (data: UserPosition) => data.id,
    WithdrawActivity: (data: WithdrawActivity) => data.id,
    RepayActivity: (data: RepayActivity) => data.id,

    // Entities with address field as key
    Erc20Token: (data: Erc20Token) => data.address,
    Hub: (data: Hub) => data.address,
    Spoke: (data: Spoke) => data.address,

    // Entities with other fields as key
    HubAsset: (data: HubAsset) => data.assetId,
    Chain: (data: Chain) => data.chainId.toString(),

    // Entities without keys will be embedded directly on the parent entity
    PaginatedResultInfo: () => null,
    PaginatedSpokePositionManagerResult: () => null,
    PaginatedSpokeUserPositionManagerResult: () => null,
    PaginatedUserHistoryResult: () => null,
    SpokeConfig: () => null,
    SpokePositionManger: () => null,
    SpokeUserPositionManger: () => null,
    SwapReceipt: () => null,
    SwapTransactionRequest: () => null,

    // Value objects and result types
    ApprovalRequired: () => null,
    APYSample: () => null,
    BigDecimalVariation: () => null,
    BigDecimalWithChange: () => null,
    CancelSwapTypedData: () => null,
    CancelSwapTypeDefinition: () => null,
    DecimalValue: () => null,
    DomainData: () => null,
    Erc20Amount: () => null,
    FiatAmount: () => null,
    FiatAmountValueVariation: () => null,
    FiatAmountWithChange: () => null,
    ForkTopUpResponse: () => null,
    HubAssetSettings: () => null,
    HubAssetSummary: () => null,
    HubAssetUserState: () => null,
    HubSummary: () => null,
    InsufficientBalanceError: () => null,
    NativeAmount: () => null,
    NativeToken: () => null,
    PercentValue: () => null,
    PercentValueVariation: () => null,
    PercentValueWithChange: () => null,
    PermitMessageData: () => null,
    PermitTypedDataResponse: () => null,
    PrepareSwapCancelResult: () => null,
    PreviewUserPositionResult: () => null,
    ReserveSettings: () => null,
    ReserveStatus: () => null,
    ReserveSummary: () => null,
    ReserveUserState: () => null,
    SwapApprovalRequired: () => null,
    SwapByIntentTypedData: () => null,
    SwapByIntentTypeDefinition: () => null,
    SwapCancelled: () => null,
    SwapExpired: () => null,
    SwapFulfilled: () => null,
    SwapOpen: () => null,
    SwapPendingSignature: () => null,
    SwapQuote: () => null,
    SwapQuoteCosts: () => null,
    TokenInfo: () => null,
    TransactionRequest: () => null,
    TypeDefinition: () => null,
    TypeField: () => null,
    UserBalance: () => null,
    UserBorrowItem: () => null,
    UserSummary: () => null,
    UserSummaryHistoryItem: () => null,
    UserSupplyItem: () => null,
  },
});
