#!/usr/bin/env tsx

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  buildSchema,
  type GraphQLInputType,
  getNamedType,
  isInputObjectType,
} from 'graphql';

const schemaPath = process.argv[2] || 'schema.graphql';
const outputPath = process.argv[3] || 'src/defaults.ts';

const schema = buildSchema(
  readFileSync(join(process.cwd(), schemaPath), 'utf8'),
);

type InputTypeInfo = {
  defaults: Record<string, unknown>;
  fields: Record<string, string>;
};

const inputTypes = Object.values(schema.getTypeMap())
  .filter(isInputObjectType)
  .filter((type) => !type.name.startsWith('__'));

const info = new Map<string, InputTypeInfo>();

for (const type of inputTypes) {
  const defaults: Record<string, unknown> = {};
  const fields: Record<string, string> = {};

  for (const field of Object.values(type.getFields())) {
    if (field.defaultValue !== undefined) {
      defaults[field.name] = field.defaultValue;
    }

    const named = getNamedType(field.type as GraphQLInputType);
    if (isInputObjectType(named)) {
      fields[field.name] = named.name;
    }
  }

  info.set(type.name, { defaults, fields });
}

// Keep only the types whose defaults are reachable, directly or through nested inputs
const reachable = new Set(
  [...info]
    .filter(([, entry]) => Object.keys(entry.defaults).length > 0)
    .map(([name]) => name),
);

let grew = true;
while (grew) {
  grew = false;
  for (const [name, entry] of info) {
    if (
      !reachable.has(name) &&
      Object.values(entry.fields).some((field) => reachable.has(field))
    ) {
      reachable.add(name);
      grew = true;
    }
  }
}

const output: Record<string, InputTypeInfo> = {};

for (const name of [...reachable].sort()) {
  const { defaults, fields } = info.get(name) as InputTypeInfo;

  output[name] = {
    defaults,
    fields: Object.fromEntries(
      Object.entries(fields).filter(([, field]) => reachable.has(field)),
    ),
  };
}

const source = `// Generated by scripts/generate-defaults.ts from schema.graphql. Do not edit.

import type { InputDefaults } from './normalize';

export const inputDefaults: InputDefaults = ${JSON.stringify(output, null, 2)};
`;

writeFileSync(join(process.cwd(), outputPath), source);

console.log(
  `Defaults for ${Object.keys(output).length} input types saved to ${outputPath}`,
);
